In [69]:
import torch
from tokenizer.tokenizer import Tokenizer
from embedding.embedding import InputEmbedding, AbsolutePositionalEncoder, PositionalEncoding

In [70]:
VOCAB_SIZE = 100256
D_MODEL = 512

In [71]:
# take input
input_text = "!"

In [72]:
tokenizer = Tokenizer()
input_encoder = InputEmbedding(vocab_size=VOCAB_SIZE, d_model=D_MODEL)
positional_encoder = PositionalEncoding(d_model=D_MODEL, max_len=512)

In [73]:
tokens = torch.tensor(tokenizer.encode(input_text))
tokens

tensor([0])

In [74]:
input_embedding = input_encoder(tokens)
input_embedding

tensor([[-1.6226e+01, -4.4898e+01, -3.8563e+01,  1.4316e+01,  7.6030e+00,
          1.1858e+01,  7.4139e+00,  2.6728e+01, -3.9134e+01,  9.6802e+00,
         -1.0527e+01,  1.3345e+01, -9.6410e+00, -2.4425e+00, -2.5968e+01,
          4.6155e+00, -2.2094e+01, -2.3788e+01,  4.6435e+00,  3.0897e+01,
          2.7834e+01, -4.7626e+01, -6.6096e+00, -3.8002e+01, -3.2453e+01,
         -2.0202e+01, -3.1341e+00,  2.3198e+01, -2.4000e+01, -2.2830e+01,
          4.8805e-01, -6.6128e+00,  1.5643e+01,  4.1995e+01, -5.3724e+01,
         -2.7704e+01, -1.3580e+01, -2.5879e+00, -1.1597e+01,  2.3698e+01,
         -2.3092e+01, -6.7876e+00, -9.3853e+00, -1.7607e+01, -3.2889e+01,
          2.5766e+01,  8.4263e+00,  2.3608e+01,  7.0257e+00,  3.4830e+01,
         -5.4225e+00, -1.5255e+01,  2.6768e+01, -1.6075e+01,  1.8622e+01,
          2.7836e+01,  1.0113e+01, -5.8826e+01,  2.2509e+01, -8.3618e+00,
          2.9388e+01,  3.1805e+01, -4.5703e+01,  3.9337e+00,  1.0705e+01,
          3.4350e+01, -2.4450e+01, -1.

In [76]:
embeddings = positional_encoder(input_embedding)
embeddings

tensor([[[[-18.0290, -48.7753, -42.8476,  ..., -18.9138,  36.1878,   0.9808],
          [-17.0940, -49.2861,  -0.0000,  ...,  -0.0000,  36.1879,   0.0000],
          [-17.0187, -50.3488, -41.8071,  ..., -18.9138,  36.1880,   0.9808],
          ...,
          [-17.9602, -48.7775, -41.9607,  ..., -18.9155,  36.2464,   0.0000],
          [-17.0587, -49.3452, -41.7922,  ..., -18.9155,   0.0000,   0.0000],
          [-17.0493, -50.4105, -42.5320,  ...,  -0.0000,  36.2466,   0.9792]]]],
       grad_fn=<MulBackward0>)